#!/bin/bash

echo "Foda-se, cansei dessa merda!"

./apply images/P148_K2/menos-pontos-it2/3271i02-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it2 && \
./apply images/P148_K2/menos-pontos-it3/3271i03-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it3 && \
./apply images/P148_K2/menos-pontos-it4/3271i04-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it4 && \
./apply images/P148_K2/menos-pontos-it5/3271i05-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it5 && \
./apply images/P148_K2/menos-pontos-it6/3271i06-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it6 && \
./apply images/P148_K2/menos-pontos-it7/3271i07-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it7 && \
./apply images/P148_K2/menos-pontos-it8/3271i08-menos-pontos-nn-model.pt  images/P148_K2 menos-pontos-it8

echo "Gloria Senhor!!!!"